export const surahs = [
  { id: 1, name: 'Al-Fatihah', arabic: 'ٱلْفَاتِحَة', isMakki: true, verses: 7 },
  { id: 2, name: 'Al-Baqarah', arabic: 'ٱلْبَقَرَة', isMakki: false, verses: 286 },
  { id: 3, name: 'Aal-E-Imran', arabic: 'آلِ عِمْرَان', isMakki: false, verses: 200 },
  { id: 4, name: 'An-Nisa', arabic: 'ٱلنِّسَاء', isMakki: false, verses: 176 },
  { id: 5, name: 'Al-Maidah', arabic: 'ٱلْمَائِدَة', isMakki: false, verses: 120 },
  { id: 6, name: 'Al-Anam', arabic: 'ٱلْأَنْعَام', isMakki: true, verses: 165 },
  { id: 7, name: 'Al-Araf', arabic: 'ٱلْأَعْرَاف', isMakki: true, verses: 206 },
  { id: 8, name: 'Al-Anfal', arabic: 'ٱلْأَنْفَال', isMakki: false, verses: 75 },
  { id: 9, name: 'At-Tawbah', arabic: 'ٱلتَّوْبَة', isMakki: false, verses: 129 },
  { id: 10, name: 'Yunus', arabic: 'يُونُس', isMakki: true, verses: 109 },
  { id: 11, name: 'Hud', arabic: 'هُود', isMakki: true, verses: 123 },
  { id: 12, name: 'Yusuf', arabic: 'يُوسُف', isMakki: true, verses: 111 },
  { id: 13, name: 'Ar-Rad', arabic: 'ٱلرَّعْد', isMakki: false, verses: 43 },
  { id: 14, name: 'Ibrahim', arabic: 'إِبْرَٰهِيم', isMakki: true, verses: 52 },
  { id: 15, name: 'Al-Hijr', arabic: 'ٱلْحِجْر', isMakki: true, verses: 99 },
  { id: 16, name: 'An-Nahl', arabic: 'ٱلنَّحْل', isMakki: true, verses: 128 },
  { id: 17, name: 'Al-Isra', arabic: 'ٱلْإِسْرَاء', isMakki: true, verses: 111 },
  { id: 18, name: 'Al-Kahf', arabic: 'ٱلْكَهْف', isMakki: true, verses: 110 },
  { id: 19, name: 'Maryam', arabic: 'مَرْيَم', isMakki: true, verses: 98 },
  { id: 20, name: 'Taha', arabic: 'طٰهٰ', isMakki: true, verses: 135 },
  { id: 21, name: 'Al-Anbiya', arabic: 'ٱلْأَنْبِيَاء', isMakki: true, verses: 112 },
  { id: 22, name: 'Al-Hajj', arabic: 'ٱلْحَجّ', isMakki: false, verses: 78 },
  { id: 23, name: 'Al-Muminun', arabic: 'ٱلْمُؤْمِنُون', isMakki: true, verses: 118 },
  { id: 24, name: 'An-Nur', arabic: 'ٱلنُّور', isMakki: false, verses: 64 },
  { id: 25, name: 'Al-Furqan', arabic: 'ٱلْفُرْقَان', isMakki: true, verses: 77 },
  { id: 26, name: 'Ash-Shuara', arabic: 'ٱلشُّعَرَاء', isMakki: true, verses: 227 },
  { id: 27, name: 'An-Naml', arabic: 'ٱلنَّمْل', isMakki: true, verses: 93 },
  { id: 28, name: 'Al-Qasas', arabic: 'ٱلْقَصَص', isMakki: true, verses: 88 },
  { id: 29, name: 'Al-Ankabut', arabic: 'ٱلْعَنْكَبُوت', isMakki: true, verses: 69 },
  { id: 30, name: 'Ar-Rum', arabic: 'ٱلرُّوم', isMakki: true, verses: 60 },
  { id: 31, name: 'Luqman', arabic: 'لُقْمَان', isMakki: true, verses: 34 },
  { id: 32, name: 'As-Sajdah', arabic: 'ٱلسَّجْدَة', isMakki: true, verses: 30 },
  { id: 33, name: 'Al-Ahzab', arabic: 'ٱلْأَحْزَاب', isMakki: false, verses: 73 },
  { id: 34, name: 'Saba', arabic: 'سَبَأ', isMakki: true, verses: 54 },
  { id: 35, name: 'Fatir', arabic: 'فَاطِر', isMakki: true, verses: 45 },
  { id: 36, name: 'Ya-Sin', arabic: 'يٰسٓ', isMakki: true, verses: 83 },
  { id: 37, name: 'As-Saffat', arabic: 'ٱلصَّافَّات', isMakki: true, verses: 182 },
  { id: 38, name: 'Sad', arabic: 'صٓ', isMakki: true, verses: 88 },
  { id: 39, name: 'Az-Zumar', arabic: 'ٱلزُّمَر', isMakki: true, verses: 75 },
  { id: 40, name: 'Ghafir', arabic: 'غَافِر', isMakki: true, verses: 85 },
  { id: 41, name: 'Fussilat', arabic: 'فُصِّلَت', isMakki: true, verses: 54 },
  { id: 42, name: 'Ash-Shura', arabic: 'ٱلشُّورىٰ', isMakki: true, verses: 53 },
  { id: 43, name: 'Az-Zukhruf', arabic: 'ٱلزُّخْرُف', isMakki: true, verses: 89 },
  { id: 44, name: 'Ad-Dukhan', arabic: 'ٱلدُّخَان', isMakki: true, verses: 59 },
  { id: 45, name: 'Al-Jathiyah', arabic: 'ٱلْجَاثِيَة', isMakki: true, verses: 37 },
  { id: 46, name: 'Al-Ahqaf', arabic: 'ٱلْأَحْقَاف', isMakki: true, verses: 35 },
  { id: 47, name: 'Muhammad', arabic: 'مُحَمَّد', isMakki: false, verses: 38 },
  { id: 48, name: 'Al-Fath', arabic: 'ٱلْفَتْح', isMakki: false, verses: 29 },
  { id: 49, name: 'Al-Hujurat', arabic: 'ٱلْحُجُرَات', isMakki: false, verses: 18 },
  { id: 50, name: 'Qaf', arabic: 'قٓ', isMakki: true, verses: 45 },
  { id: 51, name: 'Adh-Dhariyat', arabic: 'ٱلذَّارِيَات', isMakki: true, verses: 60 },
  { id: 52, name: 'At-Tur', arabic: 'ٱلطُّور', isMakki: true, verses: 49 },
  { id: 53, name: 'An-Najm', arabic: 'ٱلنَّجْم', isMakki: true, verses: 62 },
  { id: 54, name: 'Al-Qamar', arabic: 'ٱلْقَمَر', isMakki: true, verses: 55 },
  { id: 55, name: 'Ar-Rahman', arabic: 'ٱلرَّحْمَٰن', isMakki: false, verses: 78 },
  { id: 56, name: 'Al-Waqiah', arabic: 'ٱلْوَاقِعَة', isMakki: true, verses: 96 },
  { id: 57, name: 'Al-Hadid', arabic: 'ٱلْحَدِيد', isMakki: false, verses: 29 },
  { id: 58, name: 'Al-Mujadila', arabic: 'ٱلْمُجَادِلَة', isMakki: false, verses: 22 },
  { id: 59, name: 'Al-Hashr', arabic: 'ٱلْحَشْر', isMakki: false, verses: 24 },
  { id: 60, name: 'Al-Mumtahina', arabic: 'ٱلْمُمْتَحَنَة', isMakki: false, verses: 13 },
  { id: 61, name: 'As-Saff', arabic: 'ٱلصَّفّ', isMakki: false, verses: 14 },
  { id: 62, name: 'Al-Jumuah', arabic: 'ٱلْجُمُعَة', isMakki: false, verses: 11 },
  { id: 63, name: 'Al-Munafiqun', arabic: 'ٱلْمُنَافِقُون', isMakki: false, verses: 11 },
  { id: 64, name: 'At-Taghabun', arabic: 'ٱلتَّغَابُن', isMakki: false, verses: 18 },
  { id: 65, name: 'At-Talaq', arabic: 'ٱلطَّلَاق', isMakki: false, verses: 12 },
  { id: 66, name: 'At-Tahrim', arabic: 'ٱلتَّحْرِيم', isMakki: false, verses: 12 },
  { id: 67, name: 'Al-Mulk', arabic: 'ٱلْمُلْك', isMakki: true, verses: 30 },
  { id: 68, name: 'Al-Qalam', arabic: 'ٱلْقَلَم', isMakki: true, verses: 52 },
  { id: 69, name: 'Al-Haaqqa', arabic: 'ٱلْحَاقَّة', isMakki: true, verses: 52 },
  { id: 70, name: 'Al-Maarij', arabic: 'ٱلْمَعَارِج', isMakki: true, verses: 44 },
  { id: 71, name: 'Nuh', arabic: 'نُوح', isMakki: true, verses: 28 },
  { id: 72, name: 'Al-Jinn', arabic: 'ٱلْجِنّ', isMakki: true, verses: 28 },
  { id: 73, name: 'Al-Muzzammil', arabic: 'ٱلْمُزَّمِّل', isMakki: true, verses: 20 },
  { id: 74, name: 'Al-Muddaththir', arabic: 'ٱلْمُدَّثِّر', isMakki: true, verses: 56 },
  { id: 75, name: 'Al-Qiyamah', arabic: 'ٱلْقِيَامَة', isMakki: true, verses: 40 },
  { id: 76, name: 'Al-Insan', arabic: 'ٱلْإِنسَان', isMakki: false, verses: 31 },
  { id: 77, name: 'Al-Mursalat', arabic: 'ٱلْمُرْسَلَات', isMakki: true, verses: 50 },
  { id: 78, name: 'An-Naba', arabic: 'ٱلنَّبَأ', isMakki: true, verses: 40 },
  { id: 79, name: 'An-Naziat', arabic: 'ٱلنَّازِعَات', isMakki: true, verses: 46 },
  { id: 80, name: 'Abasa', arabic: 'عَبَسَ', isMakki: true, verses: 42 },
  { id: 81, name: 'At-Takwir', arabic: 'ٱلتَّكْوِير', isMakki: true, verses: 29 },
  { id: 82, name: 'Al-Infitar', arabic: 'ٱلْإِنْفِطَار', isMakki: true, verses: 19 },
  { id: 83, name: 'Al-Mutaffifin', arabic: 'ٱلْمُطَفِّفِين', isMakki: true, verses: 36 },
  { id: 84, name: 'Al-Inshiqaq', arabic: 'ٱلْإِنشِقَاق', isMakki: true, verses: 25 },
  { id: 85, name: 'Al-Buruj', arabic: 'ٱلْبُرُوج', isMakki: true, verses: 22 },
  { id: 86, name: 'At-Tariq', arabic: 'ٱلطَّارِق', isMakki: true, verses: 17 },
  { id: 87, name: 'Al-Ala', arabic: 'ٱلْأَعْلَىٰ', isMakki: true, verses: 19 },
  { id: 88, name: 'Al-Ghashiyah', arabic: 'ٱلْغَاشِيَة', isMakki: true, verses: 26 },
  { id: 89, name: 'Al-Fajr', arabic: 'ٱلْفَجْر', isMakki: true, verses: 30 },
  { id: 90, name: 'Al-Balad', arabic: 'ٱلْبَلَد', isMakki: true, verses: 20 },
  { id: 91, name: 'Ash-Shams', arabic: 'ٱلشَّمْس', isMakki: true, verses: 15 },
  { id: 92, name: 'Al-Lail', arabic: 'ٱللَّيْل', isMakki: true, verses: 21 },
  { id: 93, name: 'Ad-Duha', arabic: 'ٱلضُّحَىٰ', isMakki: true, verses: 11 },
  { id: 94, name: 'Ash-Sharh', arabic: 'ٱلشَّرْح', isMakki: true, verses: 8 },
  { id: 95, name: 'At-Tin', arabic: 'ٱلتِّين', isMakki: true, verses: 8 },
  { id: 96, name: 'Al-Alaq', arabic: 'ٱلْعَلَق', isMakki: true, verses: 19 },
  { id: 97, name: 'Al-Qadr', arabic: 'ٱلْقَدْر', isMakki: true, verses: 5 },
  { id: 98, name: 'Al-Bayyina', arabic: 'ٱلْبَيِّنَة', isMakki: false, verses: 8 },
  { id: 99, name: 'Az-Zalzalah', arabic: 'ٱلزَّلْزَلَة', isMakki: false, verses: 8 },
  { id: 100, name: 'Al-Adiyat', arabic: 'ٱلْعَادِيَات', isMakki: true, verses: 11 },
  { id: 101, name: 'Al-Qariah', arabic: 'ٱلْقَارِعَة', isMakki: true, verses: 11 },
  { id: 102, name: 'At-Takathur', arabic: 'ٱلتَّكَاثُر', isMakki: true, verses: 8 },
  { id: 103, name: 'Al-Asr', arabic: 'ٱلْعَصْر', isMakki: true, verses: 3 },
  { id: 104, name: 'Al-Humazah', arabic: 'ٱلْهُمَزَة', isMakki: true, verses: 9 },
  { id: 105, name: 'Al-Fil', arabic: 'ٱلْفِيل', isMakki: true, verses: 5 },
  { id: 106, name: 'Quraish', arabic: 'قُرَيْش', isMakki: true, verses: 4 },
  { id: 107, name: 'Al-Maun', arabic: 'ٱلْمَاعُون', isMakki: true, verses: 7 },
  { id: 108, name: 'Al-Kawthar', arabic: 'ٱلْكَوْثَر', isMakki: true, verses: 3 },
  { id: 109, name: 'Al-Kafirun', arabic: 'ٱلْكَافِرُون', isMakki: true, verses: 6 },
  { id: 110, name: 'An-Nasr', arabic: 'ٱلنَّصْر', isMakki: false, verses: 3 },
  { id: 111, name: 'Al-Masad', arabic: 'ٱلْمَسَد', isMakki: true, verses: 5 },
  { id: 112, name: 'Al-Ikhlas', arabic: 'ٱلْإِخْلَاص', isMakki: true, verses: 4 },
  { id: 113, name: 'Al-Falaq', arabic: 'ٱلْفَلَق', isMakki: true, verses: 5 },
  { id: 114, name: 'An-Nas', arabic: 'ٱلنَّاس', isMakki: true, verses: 6 }
]


export const juzs = [
  { id: 1, startSurah: "Al-Fātiḥah", reference: "1:1", arabic: "المٓ" },
  { id: 2, startSurah: "Al-Baqarah", reference: "2:142", arabic: "سَيَقُولُ" },
  { id: 3, startSurah: "Al-Baqarah", reference: "2:253", arabic: "تِلْكَ ٱلرُّسُلُ" },
  { id: 4, startSurah: "Āl-‘Imrān", reference: "3:93", arabic: "لَن تَنَالُوا۟" },
  { id: 5, startSurah: "An-Nisā’", reference: "4:24", arabic: "وَٱلْمُحْصَنَٰتُ" },
  { id: 6, startSurah: "An-Nisā’", reference: "4:148", arabic: "يَٰٓأَيُّهَا" },
  { id: 7, startSurah: "Al-Mā’idah", reference: "5:82", arabic: "وَإِذَا سَمِعُوا۟" },
  { id: 8, startSurah: "Al-An‘ām", reference: "6:111", arabic: "وَلَوْ أَنَّنَا" },
  { id: 9, startSurah: "Al-A‘rāf", reference: "7:88", arabic: "قَالَ ٱلْمَلَأُ" },
  { id: 10, startSurah: "Al-Anfāl", reference: "8:41", arabic: "وَٱعْلَمُوا۟" },
  { id: 11, startSurah: "At-Tawbah", reference: "9:93", arabic: "يَعْذِرُونَ" },
  { id: 12, startSurah: "Hūd", reference: "11:6", arabic: "وَمَا مِن دَآبَّةٍ" },
  { id: 13, startSurah: "Yūsuf", reference: "12:53", arabic: "وَمَآ أُبَرِّئُ" },
  { id: 14, startSurah: "Ibrāhīm", reference: "14:52", arabic: "رُّبَمَا" },
  { id: 15, startSurah: "Al-Ḥijr", reference: "15:1", arabic: "سُبْحَٰنَ" },
  { id: 16, startSurah: "An-Naḥl", reference: "16:50", arabic: "قَالَ أَلَمْ" },
  { id: 17, startSurah: "Al-Isrā’", reference: "17:1", arabic: "ٱقْتَرَبَ" },
  { id: 18, startSurah: "Al-Kahf", reference: "18:75", arabic: "قَالَ أَلَمْ" },
  { id: 19, startSurah: "Maryam", reference: "19:59", arabic: "وَقَالَ ٱلَّذِينَ" },
  { id: 20, startSurah: "Ṭā-Hā", reference: "20:1", arabic: "أَلَمْ نَشْرَحْ" },
  { id: 21, startSurah: "Al-Anbiyā’", reference: "21:1", arabic: "ٱقْتَرَبَ لِلنَّاسِ" },
  { id: 22, startSurah: "Al-Ḥajj", reference: "22:1", arabic: "يَٰٓأَيُّهَا ٱلنَّاسُ" },
  { id: 23, startSurah: "Al-Mu’minūn", reference: "23:1", arabic: "قَدْ أَفْلَحَ" },
  { id: 24, startSurah: "Az-Zumar", reference: "39:32", arabic: "فَمَنْ أَظْلَمُ" },
  { id: 25, startSurah: "Fuṣṣilat", reference: "41:47", arabic: "إِلَيْهِ يُرَدُّ" },
  { id: 26, startSurah: "Al-Aḥqāf", reference: "46:1", arabic: "حـمٓ" },
  { id: 27, startSurah: "Az-Zāriyāt", reference: "51:31", arabic: "قَالَ فَمَا خَطْبُكُم" },
  { id: 28, startSurah: "Al-Mujādilah", reference: "58:1", arabic: "قَدْ سَمِعَ ٱللَّهُ" },
  { id: 29, startSurah: "Al-Mulk", reference: "67:1", arabic: "تَبَارَكَ ٱلَّذِي" },
  { id: 30, startSurah: "An-Naba’", reference: "78:1", arabic: "عَمَّ" }
];



export const hizbs = [
  { id: 1, number: 1, quarter: '', surahName: 'Al-Fatihah', reference: '1:1', arabicText: 'بِسْمِ ٱللَّهِ ' },
  { id: 2, number: 1, quarter: '1/4', surahName: 'Al-Baqarah', reference: '2:1', arabicText: 'الم' },
  { id: 3, number: 1, quarter: '1/2', surahName: 'Al-Baqarah', reference: '2:75', arabicText: 'أَفَتَطْمَعُونَ' },
  { id: 4, number: 1, quarter: '3/4', surahName: 'Al-Baqarah', reference: '2:124', arabicText: 'وَإِذِ ٱبْتَلَىٰٓ' },
  { id: 5, number: 2, quarter: '', surahName: 'Al-Baqarah', reference: '2:177', arabicText: 'لَّيْسَ ٱلْبِرَّ' },
  { id: 6, number: 2, quarter: '1/4', surahName: 'Al-Baqarah', reference: '2:219', arabicText: 'يَسْـَٔلُونَكَ' },
  { id: 7, number: 2, quarter: '1/2', surahName: 'Al-Baqarah', reference: '2:253', arabicText: 'تِلْكَ ٱلرُّسُلُ' },
  { id: 8, number: 2, quarter: '3/4', surahName: 'Al-Baqarah', reference: '3:15', arabicText: 'قُلْ أَؤُنَبِّئُكُم' },
  { id: 9, number: 3, quarter: '', surahName: 'Al-Imran', reference: '3:93', arabicText: 'كُلُّ ٱلطَّعَامِ' },
  { id: 10, number: 3, quarter: '1/4', surahName: 'Al-Imran', reference: '3:171', arabicText: 'يَسْتَبْشِرُونَ' },
  { id: 11, number: 3, quarter: '1/2', surahName: 'An-Nisa', reference: '4:1', arabicText: 'يَٰٓأَيُّهَا' },
  { id: 12, number: 3, quarter: '3/4', surahName: 'An-Nisa', reference: '4:24', arabicText: 'وَٱلْمُحْصَنَٰتُ' },
  { id: 13, number: 4, quarter: '', surahName: 'An-Nisa', reference: '4:58', arabicText: 'إِنَّ ٱللَّهَ' },
  { id: 14, number: 4, quarter: '1/4', surahName: 'An-Nisa', reference: '4:88', arabicText: 'فَمَا لَكُمْ' },
  { id: 15, number: 4, quarter: '1/2', surahName: 'An-Nisa', reference: '4:135', arabicText: 'يَٰٓأَيُّهَا' },
  { id: 16, number: 4, quarter: '3/4', surahName: 'Al-Ma’idah', reference: '5:12', arabicText: 'وَلَقَدْ أَخَذَ' },
  { id: 17, number: 5, quarter: '', surahName: 'Al-Ma’idah', reference: '5:41', arabicText: 'يَٰٓأَيُّهَا ٱلرَّسُولُ' },
  { id: 18, number: 5, quarter: '1/4', surahName: 'Al-Ma’idah', reference: '5:82', arabicText: 'لَتَجِدَنَّ' },
  { id: 19, number: 5, quarter: '1/2', surahName: 'Al-An’am', reference: '6:36', arabicText: 'إِنَّمَا يَسْتَجِيبُ' },
  { id: 20, number: 5, quarter: '3/4', surahName: 'Al-An’am', reference: '6:95', arabicText: 'إِنَّ ٱللَّهَ' },
  { id: 21, number: 6, quarter: '', surahName: 'Al-A’raf', reference: '7:1', arabicText: 'المص' },
  { id: 22, number: 6, quarter: '1/4', surahName: 'Al-A’raf', reference: '7:31', arabicText: 'يَٰبَنِىٓ' },
  { id: 23, number: 6, quarter: '1/2', surahName: 'Al-A’raf', reference: '7:88', arabicText: 'قَالَ ٱلْمَلَأُ' },
  { id: 24, number: 6, quarter: '3/4', surahName: 'Al-A’raf', reference: '7:142', arabicText: 'وَوَٰعَدْنَا' },
  // Keep filling up till Hizb 60 (id: 120) i want to cryyyyy
];

