export const surahs = [
  { id: 1, name: 'Al-Fatihah', isMakki: true },
  { id: 2, name: 'Al-Baqarah', isMakki: false },
  { id: 3, name: 'Aal-E-Imran', isMakki: false },
  { id: 4, name: 'An-Nisa', isMakki: false },
  { id: 5, name: 'Al-Maidah', isMakki: false },
  { id: 6, name: 'Al-Anam', isMakki: true },
  { id: 7, name: 'Al-Araf', isMakki: true },
  { id: 8, name: 'Al-Anfal', isMakki: false },
  { id: 9, name: 'At-Tawbah', isMakki: false },
  { id: 10, name: 'Yunus', isMakki: true },
  { id: 11, name: 'Hud', isMakki: true },
  { id: 12, name: 'Yusuf', isMakki: true },
  { id: 13, name: 'Ar-Rad', isMakki: false },
  { id: 14, name: 'Ibrahim', isMakki: true },
  { id: 15, name: 'Al-Hijr', isMakki: true },
  { id: 16, name: 'An-Nahl', isMakki: true },
  { id: 17, name: 'Al-Isra', isMakki: true },
  { id: 18, name: 'Al-Kahf', isMakki: true },
  { id: 19, name: 'Maryam', isMakki: true },
  { id: 20, name: 'Taha', isMakki: true },
  { id: 21, name: 'Al-Anbiya', isMakki: true },
  { id: 22, name: 'Al-Hajj', isMakki: false },
  { id: 23, name: 'Al-Muminun', isMakki: true },
  { id: 24, name: 'An-Nur', isMakki: false },
  { id: 25, name: 'Al-Furqan', isMakki: true },
  { id: 26, name: 'Ash-Shuara', isMakki: true },
  { id: 27, name: 'An-Naml', isMakki: true },
  { id: 28, name: 'Al-Qasas', isMakki: true },
  { id: 29, name: 'Al-Ankabut', isMakki: true },
  { id: 30, name: 'Ar-Rum', isMakki: true },
  { id: 31, name: 'Luqman', isMakki: true },
  { id: 32, name: 'As-Sajdah', isMakki: true },
  { id: 33, name: 'Al-Ahzab', isMakki: false },
  { id: 34, name: 'Saba', isMakki: true },
  { id: 35, name: 'Fatir', isMakki: true },
  { id: 36, name: 'Ya-Sin', isMakki: true },
  { id: 37, name: 'As-Saffat', isMakki: true },
  { id: 38, name: 'Sad', isMakki: true },
  { id: 39, name: 'Az-Zumar', isMakki: true },
  { id: 40, name: 'Ghafir', isMakki: true },
  { id: 41, name: 'Fussilat', isMakki: true },
  { id: 42, name: 'Ash-Shura', isMakki: true },
  { id: 43, name: 'Az-Zukhruf', isMakki: true },
  { id: 44, name: 'Ad-Dukhan', isMakki: true },
  { id: 45, name: 'Al-Jathiyah', isMakki: true },
  { id: 46, name: 'Al-Ahqaf', isMakki: true },
  { id: 47, name: 'Muhammad', isMakki: false },
  { id: 48, name: 'Al-Fath', isMakki: false },
  { id: 49, name: 'Al-Hujurat', isMakki: false },
  { id: 50, name: 'Qaf', isMakki: true },
  { id: 51, name: 'Adh-Dhariyat', isMakki: true },
  { id: 52, name: 'At-Tur', isMakki: true },
  { id: 53, name: 'An-Najm', isMakki: true },
  { id: 54, name: 'Al-Qamar', isMakki: true },
  { id: 55, name: 'Ar-Rahman', isMakki: true },
  { id: 56, name: 'Al-Waqia', isMakki: true },
  { id: 57, name: 'Al-Hadid', isMakki: false },
  { id: 58, name: 'Al-Mujadila', isMakki: false },
  { id: 59, name: 'Al-Hashr', isMakki: false },
  { id: 60, name: 'Al-Mumtahina', isMakki: false },
  { id: 61, name: 'As-Saff', isMakki: false },
  { id: 62, name: 'Al-Jumuah', isMakki: false },
  { id: 63, name: 'Al-Munafiqun', isMakki: false },
  { id: 64, name: 'At-Taghabun', isMakki: false },
  { id: 65, name: 'At-Talaq', isMakki: false },
  { id: 66, name: 'At-Tahrim', isMakki: false },
  { id: 67, name: 'Al-Mulk', isMakki: true },
  { id: 68, name: 'Al-Qalam', isMakki: true },
  { id: 69, name: 'Al-Haaqqa', isMakki: true },
  { id: 70, name: 'Al-Maarij', isMakki: true },
  { id: 71, name: 'Nuh', isMakki: true },
  { id: 72, name: 'Al-Jinn', isMakki: true },
  { id: 73, name: 'Al-Muzzammil', isMakki: true },
  { id: 74, name: 'Al-Muddathir', isMakki: true },
  { id: 75, name: 'Al-Qiyamah', isMakki: true },
  { id: 76, name: 'Al-Insan', isMakki: false },
  { id: 77, name: 'Al-Mursalat', isMakki: true },
  { id: 78, name: 'An-Naba', isMakki: true },
  { id: 79, name: 'An-Naziat', isMakki: true },
  { id: 80, name: 'Abasa', isMakki: true },
  { id: 81, name: 'At-Takwir', isMakki: true },
  { id: 82, name: 'Al-Infitar', isMakki: true },
  { id: 83, name: 'Al-Mutaffifin', isMakki: true },
  { id: 84, name: 'Al-Inshiqaq', isMakki: true },
  { id: 85, name: 'Al-Buruj', isMakki: true },
  { id: 86, name: 'At-Tariq', isMakki: true },
  { id: 87, name: 'Al-Ala', isMakki: true },
  { id: 88, name: 'Al-Ghashiya', isMakki: true },
  { id: 89, name: 'Al-Fajr', isMakki: true },
  { id: 90, name: 'Al-Balad', isMakki: true },
  { id: 91, name: 'Ash-Shams', isMakki: true },
  { id: 92, name: 'Al-Lail', isMakki: true },
  { id: 93, name: 'Ad-Duhaa', isMakki: true },
  { id: 94, name: 'Ash-Sharh', isMakki: true },
  { id: 95, name: 'At-Tin', isMakki: true },
  { id: 96, name: 'Al-Alaq', isMakki: true },
  { id: 97, name: 'Al-Qadr', isMakki: true },
  { id: 98, name: 'Al-Bayyina', isMakki: false },
  { id: 99, name: 'Az-Zalzala', isMakki: false },
  { id: 100, name: 'Al-Adiyat', isMakki: true },
  { id: 101, name: "Al-Qariah", isMakki: true },
  { id: 102, name: "At-Takathur", isMakki: true },
  { id: 103, name: "Al-Asr", isMakki: true },
  { id: 104, name: "Al-Humazah", isMakki: true },
  { id: 105, name: "Al-Fil", isMakki: true },
  { id: 106, name: "Quraish", isMakki: true },
  { id: 107, name: "Al-Maun", isMakki: true },
  { id: 108, name: "Al-Kawthar", isMakki: true },
  { id: 109, name: "Al-Kafiroon", isMakki: true },
  { id: 110, name: "An-Nasr", isMakki: false },
  { id: 111, name: "Lahab", isMakki: true },
  { id: 112, name: "Al-Ikhlas", isMakki: true },
  { id: 113, name: "Al-Falaq", isMakki: true },
  { id: 114, name: "An-Nas", isMakki: true } 
];


export const juzs = [
  { id: 1, startingAyat: "Al-Fātiḥah 1:1", arabic: "المٓ" },
  { id: 2, startingAyat: "Al-Baqarah 2:142", arabic: "سَيَقُولُ" },
  { id: 3, startingAyat: "Al-Baqarah 2:253", arabic: "تِلْكَ ٱلرُّسُلُ" },
  { id: 4, startingAyat: "Āl-‘Imrān 3:93", arabic: "لَن تَنَالُوا۟" },
  { id: 5, startingAyat: "An-Nisā’ 4:24", arabic: "وَٱلْمُحْصَنَٰتُ" },
  { id: 6, startingAyat: "An-Nisā’ 4:148", arabic: "يَٰٓأَيُّهَا" },
  { id: 7, startingAyat: "Al-Mā’idah 5:82", arabic: "وَإِذَا سَمِعُوا۟" },
  { id: 8, startingAyat: "Al-An‘ām 6:111", arabic: "وَلَوْ أَنَّنَا" },
  { id: 9, startingAyat: "Al-A‘rāf 7:88", arabic: "قَالَ ٱلْمَلَأُ" },
  { id: 10, startingAyat: "Al-Anfāl 8:41", arabic: "وَٱعْلَمُوا۟" },
  { id: 11, startingAyat: "At-Tawbah 9:93", arabic: "يَعْذِرُونَ" },
  { id: 12, startingAyat: "Hūd 11:6", arabic: "وَمَا مِن دَآبَّةٍ" },
  { id: 13, startingAyat: "Yūsuf 12:53", arabic: "وَمَآ أُبَرِّئُ" },
  { id: 14, startingAyat: "Ibrāhīm 14:52", arabic: "رُّبَمَا" },
  { id: 15, startingAyat: "Al-Ḥijr 15:1", arabic: "سُبْحَٰنَ" },
  { id: 16, startingAyat: "An-Naḥl 16:50", arabic: "قَالَ أَلَمْ" },
  { id: 17, startingAyat: "Al-Isrā’ 17:1", arabic: "ٱقْتَرَبَ" },
  { id: 18, startingAyat: "Al-Kahf 18:75", arabic: "قَالَ أَلَمْ" },
  { id: 19, startingAyat: "Maryam 19:59", arabic: "وَقَالَ ٱلَّذِينَ" },
  { id: 20, startingAyat: "Ṭā-Hā 20:1", arabic: "أَلَمْ نَشْرَحْ" },
  { id: 21, startingAyat: "Al-Anbiyā’ 21:1", arabic: "ٱقْتَرَبَ لِلنَّاسِ" },
  { id: 22, startingAyat: "Al-Ḥajj 22:1", arabic: "يَٰٓأَيُّهَا ٱلنَّاسُ" },
  { id: 23, startingAyat: "Al-Mu’minūn 23:1", arabic: "قَدْ أَفْلَحَ" },
  { id: 24, startingAyat: "Az-Zumar 39:32", arabic: "فَمَنْ أَظْلَمُ" },
  { id: 25, startingAyat: "Fuṣṣilat 41:47", arabic: "إِلَيْهِ يُرَدُّ" },
  { id: 26, startingAyat: "Al-Aḥqāf 46:1", arabic: "حـمٓ" },
  { id: 27, startingAyat: "Az-Zāriyāt 51:31", arabic: "قَالَ فَمَا خَطْبُكُم" },
  { id: 28, startingAyat: "Al-Mujādilah 58:1", arabic: "قَدْ سَمِعَ ٱللَّهُ" },
  { id: 29, startingAyat: "Al-Mulk 67:1", arabic: "تَبَارَكَ ٱلَّذِي" },
  { id: 30, startingAyat: "An-Naba’ 78:1", arabic: "عَمَّ" }
];


export const hizbs = [
  { id: 1, number: 1, quarter: '', surahName: 'Al-Fatihah', reference: '1:1', arabicText: 'بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ' },
  { id: 2, number: 1, quarter: '1/4', surahName: 'Al-Baqarah', reference: '2:1', arabicText: 'الم' },
  { id: 3, number: 1, quarter: '1/2', surahName: 'Al-Baqarah', reference: '2:75', arabicText: 'أَفَتَطْمَعُونَ' },
  { id: 4, number: 1, quarter: '3/4', surahName: 'Al-Baqarah', reference: '2:124', arabicText: 'وَإِذِ ٱبْتَلَىٰٓ' },
  { id: 5, number: 2, quarter: '', surahName: 'Al-Baqarah', reference: '2:177', arabicText: 'لَّيْسَ ٱلْبِرَّ' },
  { id: 6, number: 2, quarter: '1/4', surahName: 'Al-Baqarah', reference: '2:219', arabicText: 'يَسْـَٔلُونَكَ' },
  { id: 7, number: 2, quarter: '1/2', surahName: 'Al-Baqarah', reference: '2:253', arabicText: 'تِلْكَ ٱلرُّسُلُ' },
  { id: 8, number: 2, quarter: '3/4', surahName: 'Al-Baqarah', reference: '3:15', arabicText: 'قُلْ أَؤُنَبِّئُكُم' },
  { id: 9, number: 3, quarter: '', surahName: 'Al-Imran', reference: '3:93', arabicText: 'كُلُّ ٱلطَّعَامِ' },
  { id: 10, number: 3, quarter: '1/4', surahName: 'Al-Imran', reference: '3:171', arabicText: 'يَسْتَبْشِرُونَ' },
  { id: 11, number: 3, quarter: '1/2', surahName: 'An-Nisa', reference: '4:1', arabicText: 'يَٰٓأَيُّهَا' },
  { id: 12, number: 3, quarter: '3/4', surahName: 'An-Nisa', reference: '4:24', arabicText: 'وَٱلْمُحْصَنَٰتُ' },
  { id: 13, number: 4, quarter: '', surahName: 'An-Nisa', reference: '4:58', arabicText: 'إِنَّ ٱللَّهَ' },
  { id: 14, number: 4, quarter: '1/4', surahName: 'An-Nisa', reference: '4:88', arabicText: 'فَمَا لَكُمْ' },
  { id: 15, number: 4, quarter: '1/2', surahName: 'An-Nisa', reference: '4:135', arabicText: 'يَٰٓأَيُّهَا' },
  { id: 16, number: 4, quarter: '3/4', surahName: 'Al-Ma’idah', reference: '5:12', arabicText: 'وَلَقَدْ أَخَذَ' },
  { id: 17, number: 5, quarter: '', surahName: 'Al-Ma’idah', reference: '5:41', arabicText: 'يَٰٓأَيُّهَا ٱلرَّسُولُ' },
  { id: 18, number: 5, quarter: '1/4', surahName: 'Al-Ma’idah', reference: '5:82', arabicText: 'لَتَجِدَنَّ' },
  { id: 19, number: 5, quarter: '1/2', surahName: 'Al-An’am', reference: '6:36', arabicText: 'إِنَّمَا يَسْتَجِيبُ' },
  { id: 20, number: 5, quarter: '3/4', surahName: 'Al-An’am', reference: '6:95', arabicText: 'إِنَّ ٱللَّهَ' },
  { id: 21, number: 6, quarter: '', surahName: 'Al-A’raf', reference: '7:1', arabicText: 'المص' },
  { id: 22, number: 6, quarter: '1/4', surahName: 'Al-A’raf', reference: '7:31', arabicText: 'يَٰبَنِىٓ' },
  { id: 23, number: 6, quarter: '1/2', surahName: 'Al-A’raf', reference: '7:88', arabicText: 'قَالَ ٱلْمَلَأُ' },
  { id: 24, number: 6, quarter: '3/4', surahName: 'Al-A’raf', reference: '7:142', arabicText: 'وَوَٰعَدْنَا' },
  // Keep filling up till Hizb 60 (id: 120) i want to cryyyyy
];

